# Generated by Django 4.1.4 on 2023-03-26 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('societyId', models.AutoField(primary_key=True, serialize=False)),
                ('societyName', models.CharField(max_length=200, unique=True)),
                ('societyUsername', models.CharField(max_length=200, unique=True)),
                ('societyEmail', models.EmailField(max_length=254)),
                ('totalNumberOfHouse', models.IntegerField()),
                ('totalNumberOfBuilding', models.IntegerField()),
                ('totalNumberOfFloors', models.IntegerField()),
                ('totalHouseInEachFloor', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('societyAddress', models.TextField()),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
                ('pincode', models.CharField(max_length=50)),
                ('totalAvailableParkings', models.IntegerField(default=0)),
                ('availableHouses', models.CharField(max_length=2000, null=True)),
            ],
            options={
                'db_table': 'SocietyDetail',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('houseNumber', models.CharField(max_length=100)),
                ('blockNumber', models.CharField(default='A', max_length=50)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(default='1234', max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('societyName', models.CharField(max_length=200)),
                ('totalDaysAvailable', models.IntegerField(default=0)),
                ('startDate', models.DateField(default=datetime.date(2000, 1, 1))),
                ('endDate', models.DateField(default=datetime.date(2000, 1, 3))),
                ('available', models.BooleanField(default=False)),
                ('societyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.society')),
            ],
        ),
    ]
